In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path='C:\\Users\\ASUS\\Attendance face recog\\Photos'
images=[]
classNames=[]
myList=os.listdir(path)
print(myList)
for cl in myList:
    curImg=cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Bill gates.jpg', 'Elon musk.jpg', 'Jack Ma.jpg', 'Jeff Bezos.jpg', 'Mukesh Ambani.jpg', 'Sundar Pichai.jpg']
['Bill gates', 'Elon musk', 'Jack Ma', 'Jeff Bezos', 'Mukesh Ambani', 'Sundar Pichai']


In [3]:
def findEncodings(images):
    encodeList=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode=face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

encodelistknown=findEncodings(images)
print("Encoding Complete")


Encoding Complete


In [4]:
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myData=f.readlines()
        nameList=[]
        for line in myData:
            entry=line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now=datetime.now()
            mystring=now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{mystring}') 

In [5]:
cap=cv2.VideoCapture(0)

In [6]:
while True:
    success,img=cap.read()
    imgS=cv2.resize(img,(0,0),None,0.25,0.25)
    imgS=cv2.cvtColor(imgS,cv2.COLOR_BGR2RGB)
    
    facescurr=face_recognition.face_locations(imgS)
    encodecurr=face_recognition.face_encodings(imgS,facescurr)
    for encodeface,faceloc in zip(encodecurr,facescurr):
        matches=face_recognition.compare_faces(encodelistknown,encodeface)
        facedis=face_recognition.face_distance(encodelistknown,encodeface)
        print (facedis)
        matchIndex=np.argmin(facedis)
        
        if matches[matchIndex]:
            name=classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1=faceloc
            y1,x2,y2,x1=y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
            
    cv2.imshow('Webcam',img)
    cv2.waitKey(1)

[0.82339395 0.78072862 0.77269533 0.4818468  0.80244448 0.83207717]
JEFF BEZOS
[0.71960955 0.70849951 0.88391397 0.63343592 0.84374551 0.81159301]
[0.77702007 0.79398676 0.77470269 0.52394938 0.84037296 0.82379347]
JEFF BEZOS
[0.74548053 0.70157843 0.78062551 0.56868305 0.85770355 0.84743888]
JEFF BEZOS
[0.8252547  0.775684   0.8320143  0.43391946 0.8876784  0.82436794]
JEFF BEZOS
[0.78463353 0.74351977 0.80584359 0.46589999 0.83472724 0.81006015]
JEFF BEZOS
[0.75706885 0.65321136 0.76294999 0.54250505 0.81775833 0.82710364]
JEFF BEZOS
[0.7444947  0.77185612 0.76511042 0.54349364 0.82371221 0.78530712]
JEFF BEZOS
[0.82217672 0.78060259 0.83725442 0.44012555 0.87449501 0.83523203]
JEFF BEZOS
[0.81392022 0.77177717 0.86160806 0.46699493 0.89510084 0.85237824]
JEFF BEZOS
[0.83697023 0.76686373 0.84591897 0.41062571 0.88664503 0.84944398]
JEFF BEZOS
[0.81171707 0.76276126 0.84315934 0.46073151 0.87867231 0.82636985]
JEFF BEZOS
[0.83373095 0.76324447 0.83086623 0.37767717 0.84862896 0.83030

[0.8202615  0.79054799 0.36332764 0.81647785 0.74572019 0.87165228]
JACK MA
[0.81387699 0.80295291 0.35736613 0.81026159 0.72447301 0.85636875]
JACK MA
[0.81716915 0.79334195 0.35202114 0.8141974  0.73482608 0.86358582]
JACK MA
[0.79428923 0.782136   0.34449392 0.81389875 0.7412655  0.87275398]
JACK MA
[0.78410743 0.76745006 0.38823366 0.78918394 0.71951146 0.83887971]
JACK MA
[0.7980492  0.79331886 0.34219359 0.80431165 0.74838842 0.87830533]
JACK MA
[0.80479528 0.79304195 0.32218697 0.8000565  0.75215245 0.87538271]
JACK MA
[0.78575309 0.78286661 0.3665239  0.81626962 0.74059874 0.85049025]
JACK MA
[0.80426452 0.78795112 0.35198142 0.79742061 0.73239002 0.86254211]
JACK MA
[0.80639059 0.79357014 0.33877533 0.81632928 0.73810473 0.88047227]
JACK MA
[0.80615947 0.80214613 0.35739189 0.82659597 0.72652256 0.86059445]
JACK MA
[0.79853746 0.77358403 0.38206366 0.79588405 0.74045864 0.85123445]
JACK MA
[0.77532551 0.77637516 0.34556149 0.79543099 0.74698719 0.87711405]
JACK MA
[0.81437316 

KeyboardInterrupt: 